### ISSUE TITLE
can't reach service by name

### ISSUE THREAD

**Issue by hwinkel** [pieterlange/kube-openvpn#9] opened 2016-10-29 12:47 UTC
After succesful deployment I'm able to Ping the ClusterIPs of a pod (not a service, but this might be OK) 

but how can a reach a service by name? is there any special DNS config required to push to the client like internal search domain or similar?

**Comment by pieterlange** [comment] 2016-10-29 12:57
The openvpn server should automatically push a DNS resolver and DNS search domain to the client.

I try to detect the current DNS resolver (https://github.com/pieterlange/kube-openvpn/blob/master/entrypoint.sh#L43) but you can also override it by setting `OVPN_K8S_DNS`. I don't think anyone should ever need to do this, but you can.

The DNS search domain is automatically set to `svc.cluster.local`, so you should be able to resolve `$service.$namespace`, unless you are on a recent version of OSX ([workaround](https://github.com/michthom/AlwaysAppendSearchDomains/issues/3)). You can override the search domain by setting `OVPN_K8S_DOMAIN` on the pod. I might change the deployment defaults later to search for `$ovpn_namespace.svc.cluster.local`.

Service IP's are not pingable due to the nature of service routing in kubernetes.

**Comment by pieterlange** [comment] 2016-10-29 13:02
This of course assumes you're already running kube-dns, which is a default nowadays i think.

**Comment by hwinkel** [comment] 2016-10-29 14:17
first check seems working, Thanks for the advise, will make more checks soon

**Comment by pieterlange** [comment] 2016-10-31 16:00
We confirmed this works during a talk on slack. Closing.

**Closed as completed by pieterlange** 2016-10-31 16:00 UTC
Labels: question
